version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  enable_bandit = true
  enable_mypy = true
  exclude_paths = ["tests/", "migrations/", "venv/"]
