version = 1

test_patterns = [
  ".pytest_cache/**",
  "tests/**"
]

exclude_patterns = [
  ".vscode/**",
  "flask_session/**",
  ".env",
  ".gitignore",
  "pyproject.toml",
  "README.md",
  "requirements.txt",
  "uv.lock"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"

[[transformers]]
name = "ruff"

[[transformers]]
name = "isort"