version = 1

<<<<<<< HEAD
exclude_patterns = ["data/**, .vscode/**, .pytest_cache/**, flask_session/**,"]
=======
exclude_patterns = ["data/**, .vscode/**, .pytest_cache/**, flask_session/**, "]
>>>>>>> b9114e79f332c938fc63d4a7d3f7de02416191fc

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"